ARG BASE_IMAGE=ubuntu:22.04
FROM ${BASE_IMAGE}

ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-rosdep \
 && rm -rf /var/lib/apt/lists/*

RUN rosdep init || true
RUN rosdep update

RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-humble-isaac-ros-image-proc \
    ros-humble-isaac-ros-dnn-image-encoder \
    ros-humble-isaac-ros-tensor-rt \
    ros-humble-isaac-ros-yolov8 \
    ros-humble-isaac-ros-unet \
    ros-humble-isaac-ros-stereo-image-proc \
    ros-humble-isaac-ros-zed \
    ros-humble-isaac-ros-h264-encoder \
    ros-humble-isaac-ros-examples \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /workspaces/isaac_ros-dev

COPY build/src/ ./src/

RUN --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/var/lib/apt \
    apt-get update && \
    rosdep install \
        --from-paths src \
        --ignore-src \
        --rosdistro humble \
        -r -y
