ARG BASE_IMAGE=ubuntu:22.04
FROM ${BASE_IMAGE}

# FIX: remove broken Yarn repo from base image
# TODO: make a better solution
RUN rm -f /etc/apt/sources.list.d/yarn.list \
    && rm -f /etc/apt/trusted.gpg.d/yarn.gpg \
    && rm -f /usr/share/keyrings/yarn.gpg

ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-c"]

ARG TARGETARCH
ARG TARGETPLATFORM

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-rosdep \
 && rm -rf /var/lib/apt/lists/*

RUN rosdep init || true
RUN rosdep update

RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-humble-isaac-ros-image-proc \
    ros-humble-isaac-ros-dnn-image-encoder \
    ros-humble-isaac-ros-tensor-rt \
    ros-humble-isaac-ros-yolov8 \
    ros-humble-isaac-ros-unet \
    ros-humble-isaac-ros-stereo-image-proc \
    ros-humble-isaac-ros-zed \
    ros-humble-isaac-ros-h264-encoder \
    ros-humble-isaac-ros-examples \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /workspaces/isaac_ros-dev

COPY build/src/ ./src/

RUN --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/var/lib/apt \
    apt-get update && \
    rosdep install \
        --from-paths src \
        --ignore-src \
        --rosdistro humble \
        -r -y

RUN --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/var/lib/apt \
    apt-get update && apt-get install -y --no-install-recommends \
    libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-tools \
    pkg-config \
 && rm -rf /var/lib/apt/lists/*

RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install \
        ipykernel \
        jupyter \
        roboflow \
        ultralytics \
        "requests>=2.25.1,<2.29.0" \
        "urllib3>=1.25.11,<2.0.0" \
        "requests-toolbelt>=0.9.1,<1.0.0"

RUN --mount=type=cache,target=/root/.cache/pip \
    if [ "${TARGETARCH}" = "arm64" ]; then \
        pip3 install \
          https://github.com/ultralytics/assets/releases/download/v0.0.0/onnxruntime_gpu-1.20.0-cp310-cp310-linux_aarch64.whl && \
        pip3 install \
          https://github.com/ultralytics/assets/releases/download/v0.0.0/torchvision-0.20.0a0+afc54f7-cp310-cp310-linux_aarch64.whl ; \
    else \
        pip3 install onnxruntime-gpu==1.20.0 torchvision ; \
    fi

RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install numpy==1.23.5

ENV MODEL_PATH=/app/models/objects_performance_3.2.model
